services:
  postgres:
    image: postgres:15
    container_name: autoservice-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autoservice    
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - autoservice_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d autoservice"]  
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    container_name: autoservice-flyway
    command: -url=jdbc:postgresql://postgres:5432/autoservice -user=admin -password=admin migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoservice_net
  
  postgres_replica1:
    image: postgres:15
    container_name: autoservice-postgres-replica1
    user: postgres
    environment:
      POSTGRES_PASSWORD: replicatorpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    networks:
      - autoservice_net
    command: |
      bash -c "
        until pg_isready -h autoservice-postgres -U replicator; do sleep 2; done &&
        rm -rf /var/lib/postgresql/data/* &&
        PGPASSWORD=replicatorpass pg_basebackup -h autoservice-postgres -D /var/lib/postgresql/data -U replicator -P -R &&
        exec postgres
      "

postgres_replica2:
  image: postgres:15
  container_name: autoservice-postgres-replica2
  user: postgres
  environment:
    POSTGRES_PASSWORD: replicatorpass
  ports:
    - "5434:5432"
  volumes:
    - postgres_replica2_data:/var/lib/postgresql/data
  networks:
    - autoservice_net
  # временно — без репликации, чтобы посмотреть права
  command: tail -f /dev/null

volumes:
  postgres_replica1_data:
  postgres_replica2_data:
  postgres_data:

networks:
  autoservice_net:
    driver: bridge